# Generated by Django 5.1.7 on 2025-03-08 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_register', '0001_initial'),
        ('database', '0003_coupon_one_time_use'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
            ],
            options={
                'verbose_name': 'Client Coupon',
                'verbose_name_plural': 'Client Coupons',
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('database.coupon',),
        ),
    ]
