# Generated by Django 5.1.7 on 2025-03-07 14:07

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
            ],
            options={
                'verbose_name': 'Admin Coach',
                'verbose_name_plural': 'Admin Coaches',
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('database.coach',),
        ),
    ]
