# Generated by Django 5.1.7 on 2025-03-06 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('date_to', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('frtp_date_from', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('msf_id', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=3)),
                ('zipcode', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name': 'Coach',
                'verbose_name_plural': 'Coaches',
                'db_table': 'coach',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('class_type', models.CharField(choices=[('brc', 'Basic RiderCourse'), ('ime', 'Kickstart'), ('private', 'Private'), ('src', 'Skilled RiderCourse'), ('3wbrc', '3-Wheel Basic RiderCourse')], max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'db_table': 'coupon',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Ecourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_3wbrc', models.URLField()),
                ('link_brc', models.URLField()),
                ('link_src', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'eCourse',
                'verbose_name_plural': 'eCourse',
                'db_table': 'ecourse',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('class_type', models.CharField(choices=[('brc', 'Basic RiderCourse'), ('ime', 'Kickstart'), ('private', 'Private'), ('src', 'Skilled RiderCourse'), ('3wbrc', '3-Wheel Basic RiderCourse')], max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('process_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('re_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': 'Prices',
                'db_table': 'price',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('day_type', models.CharField(choices=[('monday_tuesday', 'Monday - Tuesday'), ('thursday_friday', 'Thursday - Friday'), ('saturday_sunday', 'Saturday - Sunday'), ('sunday_monday', 'Sunday - Monday'), ('sunday', 'Sunday')], max_length=16)),
                ('seats', models.CharField(default=12, max_length=2)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_price', to='database.price', verbose_name='Class')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'db_table': 'schedule',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(null=True)),
                ('amount', models.TextField(null=True)),
                ('city', models.TextField(null=True)),
                ('class_type', models.TextField(null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('coupon_code', models.TextField(blank=True, null=True)),
                ('credit_card_number', models.TextField(null=True)),
                ('dln', models.TextField(null=True)),
                ('dls', models.TextField(null=True)),
                ('dob', models.TextField(null=True)),
                ('email', models.TextField(null=True)),
                ('first_name', models.TextField(null=True)),
                ('last_name', models.TextField(null=True)),
                ('phone', models.TextField(null=True)),
                ('schedule_date', models.TextField(null=True)),
                ('schedule_day', models.TextField(null=True)),
                ('state', models.TextField(null=True)),
                ('xpl', models.TextField(null=True)),
                ('zipcode', models.TextField(null=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_schedule', to='database.schedule', verbose_name='Schedule')),
            ],
            options={
                'verbose_name': 'Register',
                'verbose_name_plural': 'Registration',
                'db_table': 'register',
                'default_permissions': (),
            },
        ),
    ]
