# Generated by Django 5.1.7 on 2025-03-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='suffix',
            field=models.CharField(blank=True, choices=[('JR', 'JR'), ('SR', 'SR'), ('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V')], max_length=3, null=True),
        ),
    ]
