# Generated by Django 5.1.7 on 2025-03-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_register_suffix'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='one_time_use',
            field=models.BooleanField(default=False),
        ),
    ]
