# Generated by Django 6.0.5 on 2026-05-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_coupon_one_time_use'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fraud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraud_type', models.CharField(choices=[('ccn', 'Credit Card Number'), ('email', 'Email Address'), ('general', 'General'), ('ipaddress', 'IP Address')], max_length=9)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(unique=True)),
            ],
            options={
                'verbose_name': 'Fraud String',
                'verbose_name_plural': 'Fraud Strings',
                'db_table': 'fraud',
                'default_permissions': (),
            },
        ),
    ]
