# Generated by Django 6.0.5 on 2026-05-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_fraud'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='dob_age',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='ipaddress',
            field=models.TextField(null=True),
        ),
    ]
