# Generated by Django 6.0.5 on 2026-05-23 13:47

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database', '0004_fraud'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
            ],
            options={
                'verbose_name': 'Client Coupon',
                'verbose_name_plural': 'Client Coupon',
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('database.coupon',),
        ),
    ]
