# Generated by Django 5.2.7 on 2025-10-15 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_payment', '0002_coupon'),
        ('database', '0003_coupon_one_time_use'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
            ],
            options={
                'verbose_name': 'Client Register',
                'verbose_name_plural': 'Client Register',
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('database.register',),
        ),
    ]
