# Generated by Django 5.1.7 on 2025-03-06 21:22

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
            ],
            options={
                'verbose_name': 'Admin Price',
                'verbose_name_plural': 'Admin Prices',
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('database.price',),
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
            ],
            options={
                'verbose_name': 'Admin Register',
                'verbose_name_plural': 'Admin Registrations',
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('database.register',),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
            ],
            options={
                'verbose_name': 'Admin Schedule',
                'verbose_name_plural': 'Admin Schedules',
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('database.schedule',),
        ),
    ]
