# Generated by Django 6.0.5 on 2026-05-23 20:44

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database', '0005_register_dob_age_register_ipaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fraud',
            fields=[
            ],
            options={
                'verbose_name': 'Admin Fraud',
                'verbose_name_plural': 'Admin Fraud',
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('database.fraud',),
        ),
    ]
